name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:

  # 1. Build & Test
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Run Tests
        run: ./mvnw clean verify

#  # 2. Deploy to Production
#  deploy:
#    name: Deploy to Production
#    needs: test
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#    environment:
#      name: production
#      url: https://prod.my-vehicle-service.com
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Deploy to Production
#        run: echo "Auto-deploying to PRODUCTION"
